version: '2'
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ez_db
      - POSTGRES_USER=ez_user
      - POSTGRES_PASSWORD=ez_pw
    volumes:
      - ./docker-compose-database-config.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - compose_ez-postgres

networks:
  compose_ez-postgres:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.68.64.1/24